language: java
env:
  global:
    - GH_REF: github.com/w3c/wcag.git
    
git:
  depth: 3
  
before_install:
  - tar -xzvf lib/apache-ant-1.10.6-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH

script:
  - mkdir output
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/wcag.git output
  - ant deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: redesign
