language: java
before_script:
  - curl -L http://sourceforge.net/projects/saxon/files/Saxon-HE/9.5/SaxonHE9-5-1-4J.zip/download > SaxonHE9.zip
  - unzip SaxonHE9.zip

script:
  - ant -f wcag20/build.xml -lib saxon9he.jar understanding
  - ant -f wcag20/build.xml -lib saxon9he.jar techniques
