name: CI

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches: [kgf-11ty-deploy] # TODO: change to main when ready to PR

jobs:
  main:
    name: deploy (11ty)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: _site
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'
      # Remove directories before building, to clean up files that are no longer generated
      - name: Clean
        working-directory: _site
        run: rm -r techniques understanding working-examples
      - name: Build
        env:
          WCAG_MODE: editors
        run: |
          npm i
          npm run build
          cp guidelines/guidelines.css guidelines/relative-luminance.html _site/guidelines/22
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/$GITHUB_REPOSITORY/main/guidelines/index.html -o _site/guidelines/22/index.html -f  --retry 3
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/$GITHUB_REPOSITORY/main/requirements/22/index.html -o _site/requirements/22/index.html -f  --retry 3
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/$GITHUB_REPOSITORY/main/conformance-challenges/index.html -o _site/conformance-challenges/index.html -f  --retry 3
      - name: Push
        working-directory: _site
        run: |
          git config user.email 87540780+w3cgruntbot@users.noreply.github.com
          git config user.name w3cgruntbot
          git add -A .
          git commit -m ":robot: Deploy to GitHub Pages: $GITHUB_SHA from branch $GITHUB_REF"
          git push origin gh-pages
